### ISSUE TITLE
Please do not overload the Arduino C functions.

### ISSUE THREAD

**Issue by ps2chiper** [ArminJo/PWMMotorControl#1]
Hello, I found your library, and I am impressed with the level of effort you have put into it. I would like to use it for my micromouse maze crawler. I did run into an issue when I was porting your code to STM32.

attachInterrupt(uint8_t aInterruptPinNumber) 

I am still learning C++ myself, but I do recall that C functions can not be overloaded. I did look into the Arduino attachInterrupt function and there was no class to scope to, so as far as I know I had to rename your implementation of attachInterrupt to attachInterruptMember. The other issue I ran into and I think I solved, is the use of a non-static members within a static function call. I did see you worked around it by using class pointers to call the non static member functions. I did some research and I think something like this would work.

`    
    static void attach(uint8_t interruptNum, EncoderMotor *ptr);
    static void isr0();
    static void isr1();

void EncoderMotor::isr0()
{
    sPointerForInt0ISR->handleEncoderInterrupt();
}

void EncoderMotor::isr1()
{
    sPointerForInt1ISR->handleEncoderInterrupt();
}

void EncoderMotor::attach(uint8_t interruptNum, EncoderMotor *ptr)
{

    if (sPointerForInt0ISR == nullptr)
    {
        sPointerForInt0ISR = ptr;
        attachInterrupt(interruptNum, isr0, RISING);
    }
    else if (sPointerForInt1ISR == nullptr)
    {
        sPointerForInt1ISR = ptr;
        attachInterrupt(interruptNum, isr1, RISING);
    }

}`

**Comment by ArminJo** [comment]
Thanks for reporting this 🥇
